# 代理配置
agents:
  # 神秘事件研究员
  mystery_researcher:
    name: "mystery_researcher"
    type: "mystery_researcher"
    llm_type: "research"
    description: "专门研究神秘事件和未解之谜的研究员"
    capabilities:
      - "深度信息搜索"
      - "多源信息整合"
      - "假设生成"
      - "证据分析"
    tools:
      - "tavily_search"
      - "chroma_rag"
      - "spacy_analyzer"
    prompt_template: |
      你是一名专业的神秘事件研究员。你的任务是：
      1. 深入搜索和分析与神秘事件相关的信息
      2. 从多个角度收集证据和线索
      3. 生成合理的假设和推论
      4. 保持客观和批判性思维
      
      请基于以下信息进行分析：{input}
    parameters:
      max_search_results: 20
      analysis_depth: "deep"
      hypothesis_count: 3
    enabled: true

  # 学术研究员
  academic_researcher:
    name: "academic_researcher"
    type: "academic_researcher"
    llm_type: "research"
    description: "进行学术研究和文献分析的研究员"
    capabilities:
      - "学术文献搜索"
      - "引用分析"
      - "研究方法评估"
      - "同行评议"
    tools:
      - "google_search"
      - "chroma_rag"
      - "spacy_analyzer"
    prompt_template: |
      你是一名学术研究员。你的职责包括：
      1. 搜索和分析相关学术文献
      2. 评估研究方法的可靠性
      3. 识别研究中的偏见和局限性
      4. 提供基于证据的结论
      
      请分析以下研究主题：{input}
    parameters:
      citation_threshold: 10
      peer_review_required: true
    enabled: true

  # 可信度分析师
  credibility_analyzer:
    name: "credibility_analyzer"
    type: "credibility_analyzer"
    llm_type: "analysis"
    description: "分析信息源可信度和内容真实性的分析师"
    capabilities:
      - "信息源验证"
      - "事实核查"
      - "偏见检测"
      - "可信度评分"
    tools:
      - "tavily_search"
      - "beautifulsoup_extractor"
      - "spacy_analyzer"
    prompt_template: |
      你是一名可信度分析师。你需要：
      1. 评估信息源的权威性和可靠性
      2. 检查事实的准确性
      3. 识别潜在的偏见和误导信息
      4. 提供可信度评分和分析报告
      
      请分析以下信息的可信度：{input}
    parameters:
      credibility_threshold: 0.7
      fact_check_sources: 3
    enabled: true

  # 关联分析师
  correlation_analyzer:
    name: "correlation_analyzer"
    type: "correlation_analyzer"
    llm_type: "analysis"
    description: "分析事件、人物、地点之间关联关系的分析师"
    capabilities:
      - "关系网络分析"
      - "模式识别"
      - "时间序列分析"
      - "因果关系推断"
    tools:
      - "chroma_rag"
      - "spacy_analyzer"
    prompt_template: |
      你是一名关联分析师。你的任务是：
      1. 识别事件、人物、地点之间的关联
      2. 分析关系网络和模式
      3. 推断可能的因果关系
      4. 构建关联图谱
      
      请分析以下数据中的关联关系：{input}
    parameters:
      min_correlation: 0.5
      network_depth: 3
    enabled: true

  # 数据收集器
  data_collector:
    name: "data_collector"
    type: "data_collector"
    llm_type: "basic"
    description: "收集和整理各类数据的收集器"
    capabilities:
      - "网页数据抓取"
      - "结构化数据提取"
      - "数据清洗"
      - "格式转换"
    tools:
      - "beautifulsoup_extractor"
      - "playwright_extractor"
    prompt_template: |
      你是一名数据收集器。你需要：
      1. 从指定来源收集相关数据
      2. 提取结构化信息
      3. 清洗和标准化数据
      4. 确保数据质量和完整性
      
      请收集以下主题的数据：{input}
    parameters:
      max_pages: 50
      data_format: "json"
    enabled: true

  # 报告生成器
  report_generator:
    name: "report_generator"
    type: "report_generator"
    llm_type: "basic"
    description: "生成综合分析报告的生成器"
    capabilities:
      - "报告撰写"
      - "数据可视化"
      - "结论总结"
      - "建议提供"
    tools: []
    prompt_template: |
      你是一名报告生成器。你的职责是：
      1. 整合各方面的分析结果
      2. 撰写清晰、结构化的报告
      3. 提供数据支持的结论
      4. 给出可行的建议
      
      请基于以下分析结果生成报告：{input}
    parameters:
      report_format: "markdown"
      include_charts: true
    enabled: true