# 工具配置
tools:
  # 搜索引擎工具
  tavily_search:
    name: "tavily_search"
    type: "tavily"
    enabled: true
    api_config:
      api_key: "${TAVILY_API_KEY}"
      base_url: "https://api.tavily.com"
      timeout: 30
      max_retries: 3
    parameters:
      search_depth: "advanced"
      max_results: 10
      include_answer: true
      include_raw_content: false
      include_images: false

  google_search:
    name: "google_search"
    type: "google"
    enabled: false
    api_config:
      api_key: "${GOOGLE_API_KEY}"
      base_url: "https://www.googleapis.com/customsearch/v1"
    parameters:
      cx: "${GOOGLE_SEARCH_ENGINE_ID}"
      num: 10

  # RAG 提供商
  chroma_rag:
    name: "chroma_rag"
    type: "chroma"
    enabled: true
    parameters:
      persist_directory: "./data/chroma"
      collection_name: "documents"
      embedding_function: "sentence-transformers"

  # 分析引擎
  spacy_analyzer:
    name: "spacy_analyzer"
    type: "spacy"
    enabled: true
    parameters:
      model: "en_core_web_sm"
      disable: ["parser", "ner"]

  # 数据提取器
  beautifulsoup_extractor:
    name: "beautifulsoup_extractor"
    type: "beautifulsoup"
    enabled: true
    parameters:
      parser: "html.parser"
      features: ["html.parser"]

  playwright_extractor:
    name: "playwright_extractor"
    type: "playwright"
    enabled: false
    parameters:
      headless: true
      timeout: 30000
      wait_for_selector: "body"