# 系统配置
system:
  timeout: 30
  max_retries: 3
  retry_delay: 1.0
  debug_mode: false
  
  # 速率限制
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    requests_per_hour: 1000
    requests_per_day: 10000
    burst_limit: 10
  
  # 缓存配置
  caching:
    enabled: true
    ttl: 3600
    max_size: 1000
    backend: "memory"
  
  # 监控配置
  monitoring:
    enabled: true
    metrics_collection: true
    health_checks: true
    performance_tracking: true
  
  # 成本跟踪
  cost_tracking:
    enabled: true
    providers:
      openai:
        input_cost_per_1k_tokens: 0.03
        output_cost_per_1k_tokens: 0.06
      anthropic:
        input_cost_per_1k_tokens: 0.015
        output_cost_per_1k_tokens: 0.075
      google:
        input_cost_per_1k_tokens: 0.0035
        output_cost_per_1k_tokens: 0.0105
      qwen:
        input_cost_per_1k_tokens: 0.002
        output_cost_per_1k_tokens: 0.006
      zhipu:
        input_cost_per_1k_tokens: 0.005
        output_cost_per_1k_tokens: 0.005
      baidu:
        input_cost_per_1k_tokens: 0.008
        output_cost_per_1k_tokens: 0.012

# 神秘事件研究配置
mystery_events:
  credibility_threshold: 0.3
  max_search_results: 100
  time_window_days: 365
  location_radius_km: 100.0
  
  # 关键词配置
  keywords:
    ufo:
      - "UFO"
      - "不明飞行物"
      - "飞碟"
      - "外星人"
      - "alien"
      - "saucer"
      - "UAP"
      - "unidentified aerial phenomena"
      - "外星飞船"
      - "天空异象"
      - "神秘光点"
      - "不明物体"
      - "飞行器目击"
      - "外星接触"
      - "第三类接触"
    
    cryptid:
      - "大脚怪"
      - "雪人"
      - "尼斯湖水怪"
      - "天蛾人"
      - "chupacabra"
      - "bigfoot"
      - "sasquatch"
      - "yeti"
      - "loch ness monster"
      - "mothman"
      - "jersey devil"
      - "神秘生物"
      - "未知动物"
      - "隐秘动物学"
    
    paranormal:
      - "鬼魂"
      - "幽灵"
      - "灵异"
      - "超自然"
      - "ghost"
      - "spirit"
      - "paranormal"
      - "supernatural"
      - "闹鬼"
      - "灵异现象"
      - "超自然现象"
      - "鬼屋"
      - "灵魂出窍"
      - "通灵"
      - "降神"
    
    conspiracy:
      - "阴谋论"
      - "conspiracy"
      - "cover-up"
      - "秘密组织"
      - "政府掩盖"
      - "illuminati"
      - "共济会"
      - "新世界秩序"
      - "深层政府"
      - "阴谋"
      - "秘密计划"
      - "隐瞒真相"
    
    unexplained_phenomena:
      - "神秘现象"
      - "无法解释"
      - "异常现象"
      - "unexplained"
      - "anomaly"
      - "mysterious"
      - "strange"
      - "奇异事件"
      - "超常现象"
      - "不可思议"
      - "神秘事件"
      - "异常活动"
    
    ancient_mysteries:
      - "古代谜团"
      - "史前文明"
      - "失落文明"
      - "ancient mysteries"
      - "lost civilization"
      - "atlantis"
      - "金字塔"
      - "巨石阵"
      - "玛雅文明"
      - "古代外星人"
      - "史前遗迹"
      - "考古谜团"
    
    supernatural:
      - "超自然力量"
      - "神迹"
      - "奇迹"
      - "miracle"
      - "divine intervention"
      - "psychic"
      - "telepathy"
      - "预知"
      - "心灵感应"
      - "超能力"
      - "念力"
      - "透视"
      - "占卜"
      - "预言"
    
    anomalous_events:
      - "时间异常"
      - "空间扭曲"
      - "维度裂缝"
      - "时空异常"
      - "temporal anomaly"
      - "dimensional rift"
      - "反重力"
      - "磁场异常"
      - "能量异常"
      - "物理定律违背"
      - "科学无法解释"
  
  # 数据源配置
  data_sources:
    cnki:
      name: "中国知网"
      type: "ACADEMIC"
      base_url: "https://www.cnki.net"
      credibility_weight: 0.9
    
    wanfang:
      name: "万方数据"
      type: "ACADEMIC"
      base_url: "https://www.wanfangdata.com.cn"
      credibility_weight: 0.85
    
    web_of_science:
      name: "Web of Science"
      type: "ACADEMIC"
      base_url: "https://www.webofscience.com"
      credibility_weight: 0.95
    
    mufon:
      name: "MUFON Database"
      type: "WITNESS_REPORT"
      base_url: "https://www.mufon.com"
      credibility_weight: 0.6

# 搜索引擎配置
search_engines:
  tavily:
    api_key: ${TAVILY_API_KEY}
    base_url: "https://api.tavily.com"
    max_results: 10
    timeout: 30
    enabled: true
    search_depth: "advanced"
    include_answer: true
    include_raw_content: false
    include_domains: []
    exclude_domains: []
  
  google:
    api_key: ${GOOGLE_API_KEY}
    search_engine_id: ${GOOGLE_SEARCH_ENGINE_ID}
    base_url: "https://www.googleapis.com/customsearch/v1"
    max_results: 10
    timeout: 30
    enabled: true
    safe_search: "medium"
    language: "zh-CN"
    country: "CN"
  
  duckduckgo:
    base_url: "https://api.duckduckgo.com"
    max_results: 10
    timeout: 30
    enabled: true
    safe_search: "moderate"
    region: "cn-zh"
  
  bing:
    api_key: ${BING_API_KEY}
    base_url: "https://api.bing.microsoft.com/v7.0/search"
    max_results: 10
    timeout: 30
    enabled: true
    market: "zh-CN"
    safe_search: "Moderate"
  
  serper:
    api_key: ${SERPER_API_KEY}
    base_url: "https://google.serper.dev"
    max_results: 10
    timeout: 30
    enabled: true
    location: "China"
    language: "zh"

# RAG提供商配置
rag_providers:
  openai:
    api_key: ${OPENAI_API_KEY}
    base_url: "https://api.openai.com/v1"
    embedding_model: "text-embedding-3-small"
    embedding_dimensions: 1536
    max_tokens: 8192
    timeout: 30
    enabled: true
  
  pinecone:
    api_key: ${PINECONE_API_KEY}
    environment: ${PINECONE_ENVIRONMENT}
    index_name: "mystery-research"
    dimension: 1536
    metric: "cosine"
    timeout: 30
    enabled: false
  
  weaviate:
    url: ${WEAVIATE_URL}
    api_key: ${WEAVIATE_API_KEY}
    class_name: "Document"
    timeout: 30
    enabled: false
  
  chroma:
    host: "localhost"
    port: 8000
    collection_name: "mystery_research"
    timeout: 30
    enabled: false

# 分析引擎配置
analysis_engines:
  spacy:
    model: "zh_core_web_sm"
    enabled: true
    components:
      - "tagger"
      - "parser"
      - "ner"
      - "textcat"
  
  transformers:
    model: "bert-base-chinese"
    enabled: true
    device: "cpu"
    max_length: 512
  
  openai_analysis:
    api_key: ${OPENAI_API_KEY}
    base_url: "https://api.openai.com/v1"
    model: "gpt-4"
    enabled: true
    temperature: 0.1
    max_tokens: 2000
  
  # 可信度分析
  credibility:
    enabled: true
    factors:
      source_reliability: 0.3
      evidence_quality: 0.4
      expert_consensus: 0.2
      historical_precedent: 0.1
    threshold_levels:
      high: 0.8
      medium: 0.6
      low: 0.4
  
  # 关联分析
  correlation:
    enabled: true
    similarity_threshold: 0.7
    max_connections: 100
    algorithms:
      - "cosine_similarity"
      - "jaccard_similarity"
      - "semantic_similarity"
  
  # 时间线分析
  timeline:
    enabled: true
    time_window_days: 365
    cluster_threshold: 0.6
    min_events_per_cluster: 3
  
  # 自然语言处理
  nlp:
    language_detection_threshold: 0.8
    sentiment_analysis: true
    entity_extraction: true
    topic_modeling: true
    
    # 实体识别
    entities:
      - PERSON
      - LOCATION
      - ORGANIZATION
      - DATE
      - TIME
      - MONEY
      - PERCENT

# 数据提取器配置
data_extractors:
  # BeautifulSoup配置
  beautifulsoup:
    parser: "html.parser"
    features: ["html.parser", "lxml", "html5lib"]
    encoding: "utf-8"
  
  # Selenium配置
  selenium:
    driver: "chrome"
    headless: true
    window_size: [1920, 1080]
    timeout: 30
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  
  # Playwright配置
  playwright:
    browser: "chromium"
    headless: true
    viewport: {"width": 1920, "height": 1080}
    timeout: 30000
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

# 数据库配置
database:
  # Neo4j图数据库
  neo4j:
    uri: "bolt://localhost:7687"
    database: "neo4j"
    max_connection_lifetime: 3600
    max_connection_pool_size: 50
    connection_timeout: 30
    
  # Elasticsearch
  elasticsearch:
    hosts: ["http://localhost:9200"]
    timeout: 30
    max_retries: 3
    retry_on_timeout: true
    
    # 索引配置
    indices:
      mystery_events: "mystery_events"
      academic_sources: "academic_sources"
      news_articles: "news_articles"
      forum_posts: "forum_posts"
      documentaries: "documentaries"
  
  # PostgreSQL配置（可选）
  postgresql:
    host: "localhost"
    port: 5432
    database: "mystery_research"
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30

# 爬虫配置
crawler:
  # 通用设置
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  request_delay: 1.0
  random_delay_range: 0.5
  max_concurrent_requests: 5
  max_retries: 3
  timeout: 30
  
  # 页面限制
  max_pages_per_site: 50
  max_crawl_depth: 3
  max_content_length: 1048576  # 1MB
  
  # Selenium配置
  selenium:
    headless: true
    window_size: [1920, 1080]
    page_load_timeout: 30
    implicit_wait: 10
    
  # 内容过滤
  content_filter:
    min_text_length: 50
    max_text_length: 100000
    allowed_languages: ["zh", "en", "ja", "ko"]
    blocked_domains: []
    
  # 专业爬虫配置
  specialized:
    news:
      max_articles_per_site: 20
      date_range_days: 30
      credibility_threshold: 0.3
    
    forum:
      max_threads_per_forum: 50
      max_posts_per_thread: 100
      min_post_length: 20
    
    documentary:
      max_videos_per_channel: 10
      min_duration_minutes: 5
      max_duration_minutes: 180

# 工作流配置
workflow:
  # 执行限制
  max_execution_time: 3600  # 1小时
  max_concurrent_tasks: 10
  task_timeout: 300  # 5分钟
  
  # 功能开关
  features:
    auto_retry: true
    parallel_processing: true
    result_caching: true
    progress_tracking: true
  
  # 智能体配置
  agents:
    mystery_researcher:
      llm_provider: "openai"
      llm_model: "gpt-4"
      max_search_results: 50
      analysis_depth: "deep"
      credibility_threshold: 0.6
      search_engines: ["tavily", "google", "duckduckgo"]
      data_sources: ["news", "forum", "documentary", "government"]
      analysis_types: ["credibility", "correlation", "timeline"]
      max_iterations: 5
      temperature: 0.3
    
    academic_researcher:
      llm_provider: "anthropic"
      llm_model: "claude-3-opus-20240229"
      max_search_results: 30
      analysis_depth: "academic"
      credibility_threshold: 0.8
      search_engines: ["google", "tavily"]
      data_sources: ["documentary", "government", "news"]
      citation_style: "apa"
      peer_review_required: true
      max_iterations: 3
      temperature: 0.1
    
    credibility_analyzer:
      llm_provider: "openai"
      llm_model: "gpt-4"
      analysis_framework: "multi_factor"
      weight_factors:
        source_reliability: 0.3
        evidence_quality: 0.4
        expert_consensus: 0.2
        historical_precedent: 0.1
      threshold_levels:
        high: 0.8
        medium: 0.6
        low: 0.4
      temperature: 0.2
    
    data_collector:
      batch_size: 100
      concurrent_requests: 5
      rate_limit: 60  # 每分钟请求数
      retry_attempts: 3
      retry_delay: 1.0
      timeout: 30
      user_agent_rotation: true
      proxy_rotation: false
      respect_robots_txt: true
    
    report_generator:
      llm_provider: "anthropic"
      llm_model: "claude-3-sonnet-20240229"
      template: "standard"
      include_sources: true
      max_length: 5000
      sections: ["executive_summary", "findings", "analysis", "conclusions", "recommendations"]
      citation_format: "numbered"
      language: "zh-CN"
      tone: "professional"
      temperature: 0.4

# 存储配置
storage:
  # 数据目录
  data_dir: "./data"
  cache_dir: "./cache"
  temp_dir: "./temp"
  output_dir: "./output"
  logs_dir: "./logs"
  
  # 缓存配置
  cache:
    enabled: true
    expiry_hours: 24
    max_size_mb: 1000
    cleanup_interval_hours: 6
  
  # 文件格式
  formats:
    reports: ["markdown", "pdf", "json"]
    data_export: ["json", "csv", "xlsx"]
    graphs: ["gexf", "graphml", "json"]

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # 文件日志
  file:
    enabled: true
    filename: "mystery_research.log"
    max_size_mb: 10
    backup_count: 5
    rotation: "time"
  
  # 控制台日志
  console:
    enabled: true
    colored: true
  
  # 特定模块日志级别
  loggers:
    crawler: "INFO"
    analyzer: "INFO"
    database: "WARNING"
    ai: "INFO"

# 性能配置
performance:
  # 内存限制
  max_memory_mb: 2048
  memory_check_interval: 60
  
  # 并发控制
  max_concurrent_tasks: 10
  task_timeout: 300
  
  # 批处理
  batch_size: 100
  batch_timeout: 600
  
  # 连接池
  connection_pools:
    http: 10
    database: 20

# 安全配置
security:
  # API限制
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    requests_per_hour: 1000
    requests_per_day: 10000
  
  # 内容过滤
  content_filtering:
    enabled: true
    blocked_keywords: []
    allowed_file_types: ["txt", "pdf", "doc", "docx", "html", "json", "csv"]
    max_file_size_mb: 100
  
  # 数据加密
  encryption:
    enabled: false
    algorithm: "AES-256-GCM"
  
  # 访问控制
  access_control:
    enabled: false
    session_timeout_minutes: 60

# 国际化配置
i18n:
  default_language: "zh-CN"
  supported_languages:
    - "zh-CN"
    - "en-US"
    - "ja-JP"
    - "ko-KR"
  
  fallback_language: "en-US"
  
  # 日期时间格式
  datetime_formats:
    "zh-CN": "%Y年%m月%d日 %H:%M:%S"
    "en-US": "%B %d, %Y %I:%M:%S %p"
    "ja-JP": "%Y年%m月%d日 %H時%M分%S秒"
    "ko-KR": "%Y년 %m월 %d일 %H시 %M분 %S초"

# 通知配置
notifications:
  enabled: false
  
  # 邮件通知
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    use_tls: true
  
  # Slack通知
  slack:
    enabled: false
    channel: "#mystery-research"
  
  # Discord通知
  discord:
    enabled: false

# 监控配置
monitoring:
  enabled: false
  
  # 性能监控
  performance:
    enabled: false
    collection_interval: 60
    metrics:
      - "cpu_usage"
      - "memory_usage"
      - "disk_usage"
      - "network_io"
  
  # 健康检查
  health_check:
    enabled: false
    interval: 300
    endpoints:
      - "database"
      - "search_engine"
      - "ai_service"

# 开发配置
development:
  debug_mode: false
  test_mode: false
  mock_external_apis: false
  
  # 测试数据
  test_data:
    enabled: false
    sample_size: 100
    mock_responses: true
  
  # 性能分析
  profiling:
    enabled: false
    output_dir: "./profiling"
    
# 实验性功能
experimental:
  enabled: false
  
  features:
    advanced_nlp: false
    image_analysis: false
    video_analysis: false
    real_time_processing: false
    machine_learning: false